export const LANGUAGE_OPTIONS = [
  { code:'ja', label:'日本語', native:'日本語', speechLang:'ja-JP', status:'母語', aliases:['Japanese'] },
  { code:'en', label:'英語', native:'English', speechLang:'en-US' },
  { code:'fr', label:'フランス語', native:'Français', speechLang:'fr-FR' },
  { code:'es', label:'スペイン語', native:'Español', speechLang:'es-ES' },
  { code:'pt', label:'ポルトガル語', native:'Português', speechLang:'pt-BR' },
  { code:'ru', label:'ロシア語', native:'Русский', speechLang:'ru-RU' },
  { code:'de', label:'ドイツ語', native:'Deutsch', speechLang:'de-DE' },
  { code:'ar', label:'アラビア語', native:'العربية', speechLang:'ar-SA' },
  { code:'tr', label:'トルコ語', native:'Türkçe', speechLang:'tr-TR' },
  { code:'th', label:'タイ語', native:'ไทย', speechLang:'th-TH' },
  { code:'zh', label:'中国語', native:'中文', speechLang:'zh-CN' },
  { code:'yue', label:'広東語', native:'粵語', speechLang:'zh-HK', status:'学習中', aliases:['Cantonese'] },
  { code:'ko', label:'韓国語', native:'한국어', speechLang:'ko-KR' },
  { code:'pl', label:'ポーランド語', native:'Polski', speechLang:'pl-PL' },
  { code:'nl', label:'オランダ語', native:'Nederlands', speechLang:'nl-NL' },
  { code:'el', label:'ギリシャ語', native:'Ελληνικά', speechLang:'el-GR', status:'学習中', aliases:['Greek'] },
  { code:'tl', label:'タガログ語', native:'Tagalog / Filipino', speechLang:'fil-PH' },
  { code:'id', label:'インドネシア語', native:'Bahasa Indonesia', speechLang:'id-ID' },
  { code:'it', label:'イタリア語', native:'Italiano', speechLang:'it-IT' },
  { code:'vi', label:'ベトナム語', native:'Tiếng Việt', speechLang:'vi-VN' },
  { code:'bn', label:'ベンガル語', native:'বাংলা', speechLang:'bn-BD' },
  { code:'my', label:'ミャンマー語', native:'မြန်မာ', speechLang:'my-MM' },
  { code:'si', label:'シンハラ語', native:'සිංහල', speechLang:'si-LK' },
  { code:'ta', label:'タミル語', native:'தமிழ்', speechLang:'ta-IN' },
  { code:'hi', label:'ヒンディー語', native:'हिन्दी', speechLang:'hi-IN' },
  { code:'ne', label:'ネパール語', native:'नेपाली', speechLang:'ne-NP' },
  { code:'ur', label:'ウルドゥー語', native:'اردو', speechLang:'ur-PK', status:'学習中', aliases:['Urdu'] },
];

export const LANGUAGE_PROFILES = {
  ja: { countries:'日本、在外日本語コミュニティなど', speakers:'L1 約125,000,000人 / L2 学習者多数', note:'Kazu Languagesの母語。敬語、漢字、かな、文脈に応じた表現の使い分けが特徴。' },
  en: { countries:'米国、英国、カナダ、オーストラリア、インド、フィリピン、シンガポールなど', speakers:'L1 約380,000,000人 / L2 約1,135,000,000人 / 合計 約1,515,000,000人', note:'国際ビジネス、IT、学術で広く使われる世界共通語の一つ。' },
  fr: { countries:'フランス、ベルギー、スイス、カナダ、セネガル、コートジボワールなど', speakers:'L1 約79,000,000人 / L2 約238,000,000人 / 合計 約312,000,000人', note:'欧州、アフリカ、カナダに広がる国際語。外交・文化分野でも存在感が大きい。' },
  it: { countries:'イタリア、スイス、サンマリノ、バチカンなど', speakers:'合計 約85,000,000人', note:'音楽、美術、料理、ファッション分野と結びつきが強いロマンス語。' },
  es: { countries:'スペイン、メキシコ、コロンビア、アルゼンチン、ペルー、チリなど', speakers:'L1 約486,000,000人 / L2 約74,000,000人 / 合計 約560,000,000人', note:'中南米を中心に広く使われ、世界的な話者数が非常に多い。' },
  pt: { countries:'ブラジル、ポルトガル、アンゴラ、モザンビークなど', speakers:'L1 約236,000,000人 / L2 約27,000,000人 / 合計 約263,000,000人', note:'ポルトガル語圏に広がるロマンス語。ブラジル文化や音楽とも結びつきが強い。' },
  ru: { countries:'ロシア、ベラルーシ、カザフスタン、キルギス、周辺地域など', speakers:'L1 約150,000,000人 / L2 約110,000,000人 / 合計 約260,000,000人', note:'キリル文字と格変化が学習の柱。文学、科学、旧ソ連圏理解にも重要。' },
  de: { countries:'ドイツ、オーストリア、スイス、リヒテンシュタイン、ルクセンブルクなど', speakers:'L1 約75,000,000人 / L2 約58,000,000人 / 合計 約133,000,000人', note:'欧州経済、工学、哲学、クラシック音楽と関係が深い。' },
  ar: { countries:'エジプト、サウジアラビア、UAE、モロッコ、アルジェリア、イラクなど', speakers:'合計 約274,000,000〜422,000,000人（標準アラビア語・諸方言で集計差あり）', note:'地域方言と現代標準アラビア語の使い分けが特徴。中東・北アフリカに広がる。' },
  tr: { countries:'トルコ、キプロス、欧州のトルコ系コミュニティなど', speakers:'合計 約80,000,000〜90,000,000人', note:'母音調和と膠着語的な語形成が特徴。トルコ文化・歴史理解にも役立つ。' },
  th: { countries:'タイ', speakers:'合計 約60,000,000〜70,000,000人', note:'声調と独自文字が特徴。タイの文化・観光・ビジネス理解に役立つ。' },
  vi: { countries:'ベトナム', speakers:'合計 約86,000,000人', note:'声調を持ち、ラテン文字ベースの表記を使う東南アジアの主要言語。' },
  zh: { countries:'中国、台湾、シンガポール、マレーシアなど', speakers:'L1 約941,000,000人 / L2 約199,000,000人 / 合計 約1,140,000,000人', note:'ここでは普通話・標準中国語を対象。漢字と声調が学習の柱。' },
  yue: { countries:'香港、マカオ、中国広東省、在外華人コミュニティなど', speakers:'合計 約80,000,000人前後', note:'Kazu Languagesが学習中としている言語の一つ。普通話とは発音・語彙・表現に違いがある。' },
  ko: { countries:'韓国、北朝鮮、中国東北部、在外コリアン社会など', speakers:'合計 約82,000,000人', note:'ハングルは体系的な文字で、発音変化と敬語表現が重要。' },
  pl: { countries:'ポーランド、欧州・北米のポーランド系コミュニティなど', speakers:'合計 約45,000,000〜50,000,000人', note:'主に近年加わった学習言語。格変化と子音の連続が特徴的なスラヴ語。' },
  nl: { countries:'オランダ、ベルギー北部、スリナム、カリブ地域など', speakers:'合計 約24,000,000〜30,000,000人', note:'主に近年加わった学習言語。英語・ドイツ語との近さも学習の手がかりになる。' },
  el: { countries:'ギリシャ、キプロス、在外ギリシャ系コミュニティなど', speakers:'合計 約13,000,000人', note:'Kazu Languagesが学習中としている言語の一つ。ギリシャ文字と長い古典・現代文化のつながりが特徴。' },
  tl: { countries:'フィリピン、在外フィリピン人コミュニティなど', speakers:'合計 約82,000,000〜100,000,000人（フィリピノ語・タガログ語の集計で差あり）', note:'フィリピンの国語フィリピノの基盤となる言語。語順や接辞、英語・スペイン語由来語も学習ポイント。' },
  id: { countries:'インドネシア', speakers:'L1 約44,000,000人 / L2 約155,000,000人 / 合計 約199,000,000人', note:'多民族国家インドネシアの共通語。比較的規則的で学びやすい。' },
  bn: { countries:'バングラデシュ、インド東部など', speakers:'L1 約234,000,000人 / L2 約39,000,000〜43,000,000人 / 合計 約273,000,000〜284,000,000人', note:'南アジアの大言語。文学・音楽・映画文化も豊か。' },
  my: { countries:'ミャンマー', speakers:'合計 約33,000,000〜43,000,000人', note:'丸みのある文字と声調的特徴を持つ。ミャンマーの公用語。' },
  si: { countries:'スリランカ', speakers:'合計 約17,000,000〜20,000,000人', note:'スリランカ多数派の言語。独自文字とインド系語彙が特徴。' },
  ta: { countries:'インド、スリランカ、シンガポール、マレーシアなど', speakers:'合計 約87,000,000〜90,000,000人', note:'長い文学伝統を持つドラヴィダ語族の代表的言語。' },
  hi: { countries:'インド、フィジー、ネパール周辺、在外インド系社会など', speakers:'L1 約345,000,000人 / L2 約264,000,000人 / 合計 約609,000,000人', note:'インド北部を中心に広く使われ、映画・音楽文化とも結びつきが強い。' },
  ne: { countries:'ネパール、インド北東部、ブータン、在外ネパール人コミュニティなど', speakers:'合計 約30,000,000〜35,000,000人', note:'デーヴァナーガリー文字を使うインド・アーリア系の言語。ヒンディー語と文字体系が近い。' },
  ur: { countries:'パキスタン、インド(北部)、在外南アジア系コミュニティなど', speakers:'L1 約70,000,000人 / L2 約100,000,000人以上 / 合計 約230,000,000人', note:'ペルシア・アラビア文字を右から左に書くインド・アーリア系の言語。文法・語彙はヒンディー語と近く、パキスタンの国語。' },
};

export const PHRASE_CATEGORIES = [
  { code: 'greeting',   label: 'あいさつ・基本', icon: '👋' },
  { code: 'hotel',      label: 'ホテル',         icon: '🏨' },
  { code: 'restaurant', label: 'レストラン',     icon: '🍽️' },
  { code: 'transport',  label: '交通・道案内',   icon: '🚕' },
  { code: 'shopping',   label: '買い物',         icon: '🛍️' },
  { code: 'emergency',  label: '緊急時',         icon: '🚨' },
  { code: 'smalltalk',  label: '雑談',           icon: '💭' },
  { code: 'work',       label: '仕事',           icon: '💼' },
];
