/* ══════════════════════════════════════════════════
   問題データ（単語・文法）— フロントエンド／シード共通の単一情報源
   lv は TOEIC 300〜990 の10段階（1=TOEIC300 〜 10=TOEIC990）に対応する数値
══════════════════════════════════════════════════ */

export const VOCAB_DB = [
  // ── Tier 1: TOEIC 300（基礎の基礎） ──────────────────────
  {id:'v001',lv:1,word:'meeting',   jp:'かいぎ',                 ex:'The meeting starts at 9 AM.'},
  {id:'v002',lv:1,word:'email',     jp:'メール',                  ex:'Please reply to this email.'},
  {id:'v003',lv:1,word:'order',     jp:'ちゅうもんする',           ex:'Place your order online.'},
  {id:'v004',lv:1,word:'price',     jp:'ねだん',                  ex:'The price is too high.'},
  {id:'v005',lv:1,word:'open',      jp:'あける・えいぎょうする',    ex:'The store opens at 10 AM.'},
  {id:'v006',lv:1,word:'close',     jp:'しめる',                  ex:'Please close the door.'},
  {id:'v007',lv:1,word:'buy',       jp:'かう',                    ex:'I need to buy some supplies.'},
  {id:'v008',lv:1,word:'sell',      jp:'うる',                    ex:'We sell office furniture.'},
  {id:'v009',lv:1,word:'work',      jp:'はたらく',                 ex:'She works in the sales team.'},
  {id:'v010',lv:1,word:'plan',      jp:'けいかく',                 ex:'What is your plan for today?'},
  {id:'v011',lv:1,word:'help',      jp:'てつだう',                 ex:'Can you help me with this?'},
  {id:'v012',lv:1,word:'call',      jp:'でんわする',               ex:'Please call me tomorrow.'},
  {id:'v013',lv:1,word:'send',      jp:'おくる',                  ex:'Send the file to me.'},
  {id:'v014',lv:1,word:'name',      jp:'なまえ',                  ex:'Write your name here.'},
  {id:'v015',lv:1,word:'pay',       jp:'はらう',                  ex:'Pay by credit card.'},

  // ── Tier 2: TOEIC 400 ─────────────────────────────────
  {id:'v016',lv:2,word:'apply',       jp:'おうぼする・つかう',       ex:'I will apply for the job.'},
  {id:'v017',lv:2,word:'arrange',     jp:'てはいする・せいりする',    ex:'Please arrange the meeting.'},
  {id:'v018',lv:2,word:'attend',      jp:'しゅっせきする',           ex:'She will attend the conference.'},
  {id:'v019',lv:2,word:'budget',      jp:'よさん',                  ex:'We need to cut the budget.'},
  {id:'v020',lv:2,word:'cancel',      jp:'とりけす',                ex:'They canceled the order.'},
  {id:'v021',lv:2,word:'confirm',     jp:'かくにんする',             ex:'Please confirm your reservation.'},
  {id:'v022',lv:2,word:'contact',     jp:'れんらくする',             ex:'Contact us by email.'},
  {id:'v023',lv:2,word:'deliver',     jp:'はいたつする',             ex:'The package will be delivered tomorrow.'},
  {id:'v024',lv:2,word:'discount',    jp:'わりびき',                ex:'There is a 20% discount.'},
  {id:'v025',lv:2,word:'document',    jp:'しょるい・ぶんしょ',       ex:'Sign the document, please.'},
  {id:'v026',lv:2,word:'schedule',    jp:'よてい・スケジュール',      ex:'Check the schedule before you book.'},
  {id:'v027',lv:2,word:'customer',    jp:'こきゃく',                ex:'The customer asked for a refund.'},
  {id:'v028',lv:2,word:'receipt',     jp:'りょうしゅうしょ',         ex:'Keep the receipt for your records.'},
  {id:'v029',lv:2,word:'branch',      jp:'してん',                  ex:'Our branch is downtown.'},
  {id:'v030',lv:2,word:'salary',      jp:'きゅうりょう',             ex:'Her salary increased this year.'},

  // ── Tier 3: TOEIC 500 ─────────────────────────────────
  {id:'v031',lv:3,word:'employee',    jp:'じゅうぎょういん',         ex:'All employees must attend.'},
  {id:'v032',lv:3,word:'equipment',   jp:'せつび・きき',             ex:'Check the equipment before use.'},
  {id:'v033',lv:3,word:'estimate',    jp:'みつもる',                ex:'Please estimate the cost.'},
  {id:'v034',lv:3,word:'expand',      jp:'かくだいする',             ex:'The company will expand overseas.'},
  {id:'v035',lv:3,word:'extend',      jp:'えんちょうする',           ex:'They extended the deadline.'},
  {id:'v036',lv:3,word:'flexible',    jp:'じゅうなんな',             ex:'We offer flexible working hours.'},
  {id:'v037',lv:3,word:'hire',        jp:'やとう',                  ex:'We plan to hire new staff.'},
  {id:'v038',lv:3,word:'improve',     jp:'かいぜんする',             ex:'We need to improve service.'},
  {id:'v039',lv:3,word:'increase',    jp:'ふやす・ぞうかする',        ex:'Sales increased last quarter.'},
  {id:'v040',lv:3,word:'interview',   jp:'めんせつ',                ex:'He passed the interview.'},
  {id:'v041',lv:3,word:'invoice',     jp:'せいきゅうしょ',           ex:'Send the invoice by Friday.'},
  {id:'v042',lv:3,word:'manage',      jp:'かんりする',               ex:'She manages a team of ten.'},
  {id:'v043',lv:3,word:'notify',      jp:'つうちする',               ex:'Please notify us in advance.'},
  {id:'v044',lv:3,word:'offer',       jp:'ていあんする',             ex:'They offered a good price.'},
  {id:'v045',lv:3,word:'provide',     jp:'ていきょうする',           ex:'We provide free support.'},
  {id:'v046',lv:3,word:'receive',     jp:'うけとる',                ex:'Did you receive my email?'},

  // ── Tier 4: TOEIC 600 ─────────────────────────────────
  {id:'v047',lv:4,word:'accomplish',  jp:'たっせいする',             ex:'He accomplished his goal.'},
  {id:'v048',lv:4,word:'adequate',    jp:'じゅうぶんな',             ex:'The budget is adequate.'},
  {id:'v049',lv:4,word:'announce',    jp:'はっぴょうする',           ex:'The CEO will announce the plan.'},
  {id:'v050',lv:4,word:'authorize',   jp:'しょうにんする',           ex:'I authorized the purchase.'},
  {id:'v051',lv:4,word:'deadline',    jp:'しめきり',                ex:'Meet the deadline on time.'},
  {id:'v052',lv:4,word:'decline',     jp:'ことわる・へる',           ex:'Sales declined this month.'},
  {id:'v053',lv:4,word:'efficient',   jp:'こうりつてきな',           ex:'Find a more efficient method.'},
  {id:'v054',lv:4,word:'evaluate',    jp:'ひょうかする',             ex:'Evaluate the performance quarterly.'},
  {id:'v055',lv:4,word:'generate',    jp:'うみだす',                ex:'Generate more revenue.'},
  {id:'v056',lv:4,word:'implement',   jp:'じっしする',               ex:'Implement the new system.'},
  {id:'v057',lv:4,word:'reimburse',   jp:'はらいもどす',             ex:'We will reimburse your travel costs.'},
  {id:'v058',lv:4,word:'vendor',      jp:'ぎょうしゃ',               ex:'We chose a new vendor this year.'},
  {id:'v059',lv:4,word:'warranty',    jp:'ほしょう',                ex:'The product has a two-year warranty.'},
  {id:'v060',lv:4,word:'shipment',    jp:'しゅっか・とうそう',        ex:'The shipment arrived late.'},

  // ── Tier 5: TOEIC 700 ─────────────────────────────────
  {id:'v061',lv:5,word:'negotiate',   jp:'こうしょうする',           ex:'Negotiate a better deal.'},
  {id:'v062',lv:5,word:'objective',   jp:'もくひょう',               ex:'Set clear objectives.'},
  {id:'v063',lv:5,word:'opportunity', jp:'きかい',                  ex:'This is a great opportunity.'},
  {id:'v064',lv:5,word:'postpone',    jp:'えんきする',               ex:'Postpone the launch event.'},
  {id:'v065',lv:5,word:'priority',    jp:'ゆうせんじこう',           ex:'Set your priorities clearly.'},
  {id:'v066',lv:5,word:'promote',     jp:'しょうしんさせる',         ex:'She was promoted to manager.'},
  {id:'v067',lv:5,word:'proposal',    jp:'ていあんしょ',             ex:'Submit the proposal by Monday.'},
  {id:'v068',lv:5,word:'require',     jp:'ひつようとする',           ex:'The job requires experience.'},
  {id:'v069',lv:5,word:'revenue',     jp:'しゅうえき',               ex:'Annual revenue increased.'},
  {id:'v070',lv:5,word:'productive',  jp:'せいさんてきな',           ex:'Have a productive meeting.'},
  {id:'v071',lv:5,word:'contribute',  jp:'こうけんする',             ex:'She contributed to the project.'},
  {id:'v072',lv:5,word:'collaborate', jp:'きょうりょくする',         ex:'Let\'s collaborate on this project.'},
  {id:'v073',lv:5,word:'compensate',  jp:'ほしょうする',             ex:'We will compensate for the delay.'},
  {id:'v074',lv:5,word:'comply',      jp:'じゅんしゅする',           ex:'You must comply with the rules.'},
  {id:'v075',lv:5,word:'conduct',     jp:'じっしする',               ex:'They conducted a survey.'},

  // ── Tier 6: TOEIC 730 ─────────────────────────────────
  {id:'v076',lv:6,word:'outsource',   jp:'がいぶにいたくする',        ex:'They outsourced IT support.'},
  {id:'v077',lv:6,word:'inventory',   jp:'ざいこ',                  ex:'Check the inventory levels.'},
  {id:'v078',lv:6,word:'consequence', jp:'けっか・えいきょう',        ex:'Consider the consequences.'},
  {id:'v079',lv:6,word:'approach',    jp:'ちかづく・アプローチ',      ex:'We need a new approach.'},
  {id:'v080',lv:6,word:'complaint',   jp:'くじょう',                ex:'We received a complaint.'},
  {id:'v081',lv:6,word:'streamline',  jp:'こうりつかする',           ex:'Streamline the approval process.'},
  {id:'v082',lv:6,word:'liability',   jp:'ふさい・せきにん',         ex:'The company faces legal liability.'},
  {id:'v083',lv:6,word:'clientele',   jp:'こきゃくそう',             ex:'Our clientele is mostly corporate.'},
  {id:'v084',lv:6,word:'turnover',    jp:'りてん率・そりあげだか',    ex:'Staff turnover has increased.'},
  {id:'v085',lv:6,word:'endorse',     jp:'しじする・こうにんする',    ex:'The board endorsed the plan.'},

  // ── Tier 7: TOEIC 800 ─────────────────────────────────
  {id:'v086',lv:7,word:'acquisition', jp:'ばいしゅう',               ex:'The acquisition was completed.'},
  {id:'v087',lv:7,word:'allocate',    jp:'わりあてる',               ex:'Allocate resources wisely.'},
  {id:'v088',lv:7,word:'ambiguous',   jp:'あいまいな',               ex:'The instructions are ambiguous.'},
  {id:'v089',lv:7,word:'benchmark',   jp:'きじゅん・ひょうじゅん',    ex:'Set a performance benchmark.'},
  {id:'v090',lv:7,word:'contingency', jp:'ふそくのじたい',           ex:'Prepare a contingency plan.'},
  {id:'v091',lv:7,word:'deplete',     jp:'こかつさせる',             ex:'Resources are being depleted.'},
  {id:'v092',lv:7,word:'discrepancy', jp:'そうい・むじゅん',          ex:'There is a discrepancy in the report.'},
  {id:'v093',lv:7,word:'fiscal',      jp:'ざいせいの',               ex:'The fiscal year ends in March.'},
  {id:'v094',lv:7,word:'fluctuate',   jp:'へんどうする',             ex:'Prices fluctuate daily.'},
  {id:'v095',lv:7,word:'leverage',    jp:'かつようする',             ex:'Leverage your network.'},
  {id:'v096',lv:7,word:'mitigate',    jp:'かんわする',               ex:'Mitigate the financial risk.'},
  {id:'v097',lv:7,word:'obsolete',    jp:'じだいおくれの',           ex:'This technology is obsolete.'},
  {id:'v098',lv:7,word:'paradigm',    jp:'パラダイム',               ex:'A paradigm shift in business.'},
  {id:'v099',lv:7,word:'procurement', jp:'ちょうたつ',               ex:'Procurement costs rose.'},
  {id:'v100',lv:7,word:'reconcile',   jp:'てらしあわせる',           ex:'Reconcile the accounts.'},

  // ── Tier 8: TOEIC 860 ─────────────────────────────────
  {id:'v101',lv:8,word:'restructure', jp:'さいへんする',             ex:'The company will restructure.'},
  {id:'v102',lv:8,word:'scrutinize',  jp:'せいさする',               ex:'Scrutinize the contract carefully.'},
  {id:'v103',lv:8,word:'stipulate',   jp:'きていする',               ex:'The contract stipulates the terms.'},
  {id:'v104',lv:8,word:'subsidiary',  jp:'こがいしゃ',               ex:'A wholly owned subsidiary.'},
  {id:'v105',lv:8,word:'viable',      jp:'じっこうかのうな',         ex:'A viable business model.'},
  {id:'v106',lv:8,word:'expenditure', jp:'ししゅつ',                ex:'Cut unnecessary expenditure.'},
  {id:'v107',lv:8,word:'divest',      jp:'ばいきゃくする',           ex:'They decided to divest the division.'},
  {id:'v108',lv:8,word:'accrue',      jp:'つみたつ・はっせいする',    ex:'Interest will accrue monthly.'},
  {id:'v109',lv:8,word:'depreciate',  jp:'げんかしょうきゃくする',    ex:'Equipment depreciates over time.'},
  {id:'v110',lv:8,word:'indemnify',   jp:'ほしょうする（そんがい）',   ex:'The clause indemnifies both parties.'},

  // ── Tier 9: TOEIC 900 ─────────────────────────────────
  {id:'v111',lv:9,word:'amalgamate',  jp:'がっぺいする',             ex:'The two firms will amalgamate.'},
  {id:'v112',lv:9,word:'arbitrate',   jp:'ちゅうさいする',           ex:'A third party will arbitrate.'},
  {id:'v113',lv:9,word:'bureaucracy', jp:'かんりょうしゅぎ',         ex:'Cut through the bureaucracy.'},
  {id:'v114',lv:9,word:'capitalize',  jp:'かつようする',             ex:'Capitalize on the opportunity.'},
  {id:'v115',lv:9,word:'enumerate',   jp:'れっきょする',             ex:'Enumerate the key findings.'},
  {id:'v116',lv:9,word:'ratify',      jp:'ひじゅんする・しょうにんする',ex:'The board ratified the merger.'},
  {id:'v117',lv:9,word:'circumvent',  jp:'かいひする',               ex:'They tried to circumvent the regulation.'},
  {id:'v118',lv:9,word:'preclude',    jp:'ふかのうにする・ふせぐ',    ex:'The clause precludes further claims.'},
  {id:'v119',lv:9,word:'exacerbate',  jp:'あっかさせる',             ex:'Delays exacerbated the shortage.'},
  {id:'v120',lv:9,word:'expedite',    jp:'そくしんする',             ex:'Please expedite the shipment.'},

  // ── Tier 10: TOEIC 990（満点レベル） ──────────────────
  {id:'v121',lv:10,word:'inaugurate', jp:'しゅうにんさせる',         ex:'The president was inaugurated.'},
  {id:'v122',lv:10,word:'tangible',   jp:'ゆうけいの・ぐたいてきな',  ex:'Show tangible results.'},
  {id:'v123',lv:10,word:'trajectory', jp:'きせき・しんろ',           ex:'The growth trajectory is positive.'},
  {id:'v124',lv:10,word:'unanimous',  jp:'ぜんいんいっちの',         ex:'A unanimous decision was reached.'},
  {id:'v125',lv:10,word:'commensurate',jp:'つりあった',              ex:'Salary commensurate with experience.'},
  {id:'v126',lv:10,word:'perfunctory',jp:'おざなりな・けいしきてきな',ex:'He gave a perfunctory response.'},
  {id:'v127',lv:10,word:'vindicate', jp:'せいとうせいをしょうめいする',ex:'The results vindicated her decision.'},
  {id:'v128',lv:10,word:'exigent',    jp:'きんきゅうの',             ex:'This is an exigent matter.'},
  {id:'v129',lv:10,word:'onerous',    jp:'めんどうな・おもい',       ex:'The terms are onerous for small firms.'},
  {id:'v130',lv:10,word:'proclivity', jp:'けいこう・へき',           ex:'He has a proclivity for detail.'},
];

export const GRAMMAR_DB = [
  // ── Tier 1: TOEIC 300 ────────────────────────────────
  {id:'g001',lv:1,
   q:'The meeting _____ at 9 AM tomorrow.',
   choices:['start','starts','starting','started'], ans:1,
   exp:'3人称単数現在形 → starts'},
  {id:'g002',lv:1,
   q:'She _____ in the sales team.',
   choices:['work','works','working','worked'], ans:1,
   exp:'3人称単数現在形 → works'},
  {id:'g003',lv:1,
   q:'Please send _____ the file.',
   choices:['I','me','my','mine'], ans:1,
   exp:'動詞の目的語には目的格 → me'},

  // ── Tier 2: TOEIC 400 ────────────────────────────────
  {id:'g004',lv:2,
   q:'Please send the report _____ Friday.',
   choices:['in','on','at','by'], ans:3,
   exp:'by = 〜までに（期限）'},
  {id:'g005',lv:2,
   q:'She has worked here _____ five years.',
   choices:['since','for','during','from'], ans:1,
   exp:'for = 期間の長さ'},
  {id:'g006',lv:2,
   q:'The package _____ delivered yesterday.',
   choices:['is','was','were','be'], ans:1,
   exp:'過去の受動態 → was + 過去分詞'},

  // ── Tier 3: TOEIC 500 ────────────────────────────────
  {id:'g007',lv:3,
   q:'We need _____ the budget before Friday.',
   choices:['approve','approves','approved','to approve'], ans:3,
   exp:'need to do → to + 動詞原形'},
  {id:'g008',lv:3,
   q:'_____ of the employees attended the seminar.',
   choices:['Much','Every','All','Each'], ans:2,
   exp:'All of the employees = 全従業員'},
  {id:'g009',lv:3,
   q:'Could you _____ me with this task?',
   choices:['help','helping','helped','to help'], ans:0,
   exp:'Could you + 動詞原形（助動詞の後は原形）'},

  // ── Tier 4: TOEIC 600 ────────────────────────────────
  {id:'g010',lv:4,
   q:'The new product will be launched _____ next month.',
   choices:['in','on','at','（不要）'], ans:3,
   exp:'next month などには前置詞不要'},
  {id:'g011',lv:4,
   q:'The manager suggested _____ the deadline.',
   choices:['extend','to extend','extending','extended'], ans:2,
   exp:'suggest + 動名詞（〜ing）'},
  {id:'g012',lv:4,
   q:'_____ the heavy traffic, she arrived on time.',
   choices:['Despite','Although','Because','Since'], ans:0,
   exp:'Despite + 名詞句（前置詞）'},

  // ── Tier 5: TOEIC 700 ────────────────────────────────
  {id:'g013',lv:5,
   q:'The report _____ by the time the boss arrived.',
   choices:['has been completed','was completing','had been completed','completed'], ans:2,
   exp:'過去完了受動態 → had been done'},
  {id:'g014',lv:5,
   q:'We are considering _____ a new office in Tokyo.',
   choices:['open','to open','opening','opened'], ans:2,
   exp:'consider + 動名詞（〜ing）'},
  {id:'g015',lv:5,
   q:'_____ the project is approved, we will begin immediately.',
   choices:['Once','Until','Unless','Though'], ans:0,
   exp:'Once = 〜したらすぐに'},

  // ── Tier 6: TOEIC 730 ────────────────────────────────
  {id:'g016',lv:6,
   q:'Sales have increased _____ 15% compared to last year.',
   choices:['by','at','in','for'], ans:0,
   exp:'変化の幅には by（by 15% = 15%増）'},
  {id:'g017',lv:6,
   q:'Employees are required _____ safety regulations.',
   choices:['follow','follows','following','to follow'], ans:3,
   exp:'be required to do = 〜することが求められる'},
  {id:'g018',lv:6,
   q:'The CEO, _____ speech inspired everyone, retired last year.',
   choices:['who','whose','whom','which'], ans:1,
   exp:'whose + 名詞 = 〜の（関係代名詞所有格）'},

  // ── Tier 7: TOEIC 800 ────────────────────────────────
  {id:'g019',lv:7,
   q:'Had the contract _____ earlier, we would have saved costs.',
   choices:['reviewed','been reviewed','review','reviewing'], ans:1,
   exp:'仮定法過去完了受動態 → Had S been done'},
  {id:'g020',lv:7,
   q:'_____ to attend the conference, the director sent a representative.',
   choices:['Unable','Being unable','Not able','Inability'], ans:0,
   exp:'分詞構文の形容詞型 → Unable to do'},
  {id:'g021',lv:7,
   q:'The acquisition deal is contingent _____ board approval.',
   choices:['for','on','with','at'], ans:1,
   exp:'be contingent on〜 = 〜次第である'},

  // ── Tier 8: TOEIC 860 ────────────────────────────────
  {id:'g022',lv:8,
   q:'No sooner _____ the meeting ended than the phone rang.',
   choices:['had','has','have','did'], ans:0,
   exp:'No sooner had S done... than〜（倒置形）'},
  {id:'g023',lv:8,
   q:'The new policy, _____ effective next month, will affect all staff.',
   choices:['becomes','becoming','to become','become'], ans:1,
   exp:'分詞構文（現在分詞）→ becoming'},
  {id:'g024',lv:8,
   q:'It is imperative that the data _____ backed up daily.',
   choices:['is','was','be','being'], ans:2,
   exp:'imperative 後の that節 → 仮定法現在（動詞原形）'},

  // ── Tier 9: TOEIC 900 ────────────────────────────────
  {id:'g025',lv:9,
   q:'Were the board _____ to reject the proposal, the merger would collapse.',
   choices:['is','was','were','to be'], ans:3,
   exp:'倒置の仮定法 Were S to do = もしSが〜するとしたら'},
  {id:'g026',lv:9,
   q:'The findings, _____ from years of research, remain controversial.',
   choices:['derive','derived','deriving','to derive'], ans:1,
   exp:'過去分詞の分詞構文 → derived from〜（〜から導かれた）'},
  {id:'g027',lv:9,
   q:'Rarely _____ such a comprehensive report been produced.',
   choices:['has','have','had','did'], ans:1,
   exp:'否定副詞 Rarely が文頭 → 倒置（has/have + 過去分詞）'},

  // ── Tier 10: TOEIC 990（満点レベル） ──────────────────
  {id:'g028',lv:10,
   q:'So thorough _____ the audit that no discrepancies were found.',
   choices:['was','is','were','be'], ans:0,
   exp:'So + 形容詞 が文頭 → 倒置（was the audit）'},
  {id:'g029',lv:10,
   q:'The committee recommended that the policy _____ revised immediately.',
   choices:['is','was','be','being'], ans:2,
   exp:'recommend that節 → 仮定法現在（動詞原形 be）'},
  {id:'g030',lv:10,
   q:'Not until the final quarter _____ the true impact become apparent.',
   choices:['did','does','had','was'], ans:0,
   exp:'Not until〜 が文頭 → 倒置（did + 主語 + 動詞原形）'},
];
